Migration guide for 0.2.0
Kotlin/kotlinx-rpc pull request #113
Opened 2024-06-24 14:18 UTC by Mr3zee

**Subsystem**
Docs

**Problem Description**
0.2.0 contains a lot of incompatibilities

**Solution**
Provide migration guide for users

2024-06-25 09:53 UTC, vnikolova requested changes

2024-06-25 09:53 UTC, vnikolova commented on docs/pages/kotlinx-rpc/rpc.tree
> +    <toc-element topic="versions.topic">
For consistency, I think we should keep the expandable `toc-element` empty. Also, instead of nesting it might be better to separate the topics.  So this would be the structure:

Versioning (versions.topic)
Releases (empty) -> 0.2.0 (0-2-0.topic)

2024-06-25 09:53 UTC, vnikolova commented on docs/pages/kotlinx-rpc/topics/0-2-0.topic
> +        This guide contains full list of incompatibles changes.
```suggestion
        This guide contains a full list of all incompatible changes.
```

2024-06-25 09:53 UTC, vnikolova commented on docs/pages/kotlinx-rpc/topics/0-2-0.topic
> +        <code>0.2.0</code> is not compatible with previous <code>0.1.0</code> release.
```suggestion
        Version <code>0.2.0</code> introduces changes that are not compatible with the previous <code>0.1.0</code> release.
```

2024-06-25 09:53 UTC, vnikolova commented on docs/pages/kotlinx-rpc/topics/0-2-0.topic
> +        The full list of new names and changes is present below
```suggestion
        Below is the complete list of new names and changes.
```

2024-06-25 09:53 UTC, vnikolova commented on docs/pages/kotlinx-rpc/topics/0-2-0.topic
> +        (only <code>artifactId</code> are shown, <code>groupId</code> stayed the same):
```suggestion
        Note that only <code>artifactId</code> is shown; the <code>groupId</code> remains unchanged:
```

2024-06-25 09:53 UTC, vnikolova commented on docs/pages/kotlinx-rpc/topics/0-2-0.topic
> +            Prior to this release, all artifacts were versioned with еру Kotlin prefix for multiple versions of Kotlin:
What is "epy" Kotlin prefix? Looks like a typo.

2024-06-25 09:53 UTC, vnikolova commented on docs/pages/kotlinx-rpc/topics/0-2-0.topic
> +            This approached proved to be hard for the third-party library developers,
```suggestion
            This approach proved challenging for the third-party library developers,
```

2024-06-25 09:53 UTC, vnikolova commented on docs/pages/kotlinx-rpc/topics/0-2-0.topic
> +            as it is not obvious which version should they use for their artifacts.
```suggestion
            as it was not clear which version they should use for their artifacts.
```

2024-06-25 09:53 UTC, vnikolova commented on docs/pages/kotlinx-rpc/topics/0-2-0.topic
> +            From now on, only code-generation artifacts would contain the explicit Kotlin version.
```suggestion
            From now on, only code-generation artifacts will contain the explicit Kotlin version.
```

2024-06-25 09:53 UTC, vnikolova commented on docs/pages/kotlinx-rpc/topics/0-2-0.topic
> +            All other artifacts will have a simple version like this:
```suggestion
            All other artifacts will use a simplified versioning format like this:
```

2024-06-25 09:53 UTC, vnikolova commented on docs/pages/kotlinx-rpc/topics/0-2-0.topic
> +            In your gradle build scripts (<code>build.gradle.kts</code>) you need to change the repository to consume artifacts from.
```suggestion
            In your gradle build scripts (<code>build.gradle.kts</code>) you need to update the repository to ensure you consume the correct artifacts.
```

2024-06-25 10:01 UTC, vnikolova commented
@Mr3zee Sorry for the large amount of comments 😄  I just rediscovered the "suggestion" feature. Let me know if it is better for text edits.

2024-06-25 14:00 UTC, Mr3zee commented
@vnikolova that's no problem, thank you for the review!

2024-06-27 08:24 UTC, Mr3zee commented on docs/pages/kotlinx-rpc/topics/0-2-0.topic
> +            Prior to this release, all artifacts were versioned with еру Kotlin prefix for multiple versions of Kotlin:
It's 'the' with Russian keyboard layout 😅

2024-06-27 08:27 UTC, Mr3zee commented on docs/pages/kotlinx-rpc/rpc.tree
> +    <toc-element topic="versions.topic">
@vnikolova shall we name it `Migrations` or similar, so that it would be obvious why some are skipped for example (as nothing breaking was introduced)? And also it would be easier to find it someone specifically looks for a migration guide?

2024-06-27 13:32 UTC, merged