Krpc/fix call cancellation
Kotlin/kotlinx-rpc pull request #141
Opened 2024-07-23 12:48 UTC by Mr3zee

**Subsystem**
kRPC protocol

**Problem Description**
- Requests do not cancel on service/client cancellation
- Transport cancels abruptly in Ktor resulting in error messages in log

**Solution**
- Handle service/client cancellation case
- Return null in `RPCTransport` receive when messages ended

2024-07-23 12:53 UTC, Mr3zee commented
Partially fixes #100

2024-07-24 14:10 UTC, e5l requested changes

2024-07-24 14:10 UTC, e5l commented on core/src/commonMain/kotlin/kotlinx/rpc/RPCTransport.kt
> +     * @return received RPC message or null if closed.
Please consider checking coroutines Channel API for receive

2024-07-26 05:48 UTC, e5l approved these changes

2024-07-26 07:58 UTC, merged