Release 0.2.3
Kotlin/kotlinx-rpc pull request #169
Opened 2024-08-19 12:41 UTC by Mr3zee

Release of the 0.2.3 version:
- Update to K2 (2.0.0, 2.0.10)
- Support of 1.9.25
- APIs movements

This PR:
- Migration guide
- bump version
- update CHANGELOG.md

2024-08-19 12:42 UTC, Mr3zee commented
@vnikolova can I please ask you to review `docs/pages/kotlinx-rpc/topics/0-2-3.topic`?

2024-08-19 12:49 UTC, e5l approved these changes

2024-08-19 15:12 UTC, vnikolova requested changes
Looks good, just some minor tweaks in my comments.

2024-08-19 15:12 UTC, vnikolova commented on docs/pages/kotlinx-rpc/topics/0-2-3.topic
> +        If your project uses Kotlin 2.0 (stable versions of 2.0.0, 2.0.10 as of 0.2.3 release),
The text in parentheses can be removed.

2024-08-19 15:12 UTC, vnikolova commented on docs/pages/kotlinx-rpc/topics/0-2-3.topic
> +        caches</a>
```suggestion
        caches</a>.
```

2024-08-19 15:12 UTC, vnikolova commented on docs/pages/kotlinx-rpc/topics/0-2-3.topic
> +        <list>
This list will look nicer in a [table](https://www.jetbrains.com/help/writerside/tables.html). You can have one table with two columns: `0.2.2` and `0.2.3` and the names under each.

2024-08-19 15:27 UTC, vnikolova approved these changes

2024-08-20 11:03 UTC, Mr3zee commented
Closed in favor of #171

2024-08-20 11:03 UTC, closed without merging